#!/bin/bash

set -e

. version

wget http://downloads.sourceforge.net/project/kanapi/images/v${KANAPI_VER}/sbs-docker-${VER}.tar.xz
cat Dockerfile.template | sed "s/VER/${VER}/" > Dockerfile
docker build -t kanapi/kanapi-${NAME}:${VER} .
docker push kanapi/kanapi-${NAME}:${VER}

