#!/bin/bash
set -e
. version

pushd ../sbs-docker/interactive/
./create_sbs_docker
popd

cp ../sbs-docker/interactive/kanapi/kanapi_system/sbs/sbs-docker-${KANAPI_VER}.${SBS_BUILD}.tar.xz .
./make_image

#BRANCH=`git rev-parse --abbrev-ref HEAD`
#if [ "${BRANCH}" = "master" ]
#then
#	docker push kanapi/kanapi-${NAME}:${VER}
#else
#	echo "don't push from ${BRANCH} branch"
#fi


