FROM kanapi/kanapi-BASE_IMAGE
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
ENV HOME=/kanapi_0.11/home
COPY kanapi /kanapi_build/kanapi
RUN mkdir -p ${HOME}/src; cd /kanapi_build/kanapi/kanapi_system/cbs/build ; ./install cbs verbose
CMD ["/bin/bash"]
