FROM kanapi/kanapi-BASE_IMAGE
MAINTAINER Jacek Danecki <jacek.m.danecki@gmail.com>
ENV HOME=/kanapi_0.10/home
COPY kanapi /kanapi_build/kanapi
RUN cd /kanapi_build/kanapi/kanapi_system/gui/build && ./install gui verbose
CMD ["/bin/bash"]
