#!/bin/bash

. version

USE_LOCAL=1
DIR=`pwd`
REPO_BASE=`git rev-parse --show-toplevel`
KANAPI_VER=`cat ${REPO_BASE}/kanapi_system/scripts/KANAPI_VER`

if [ ! -d ${HOME}/src ] ; then mkdir ${HOME}/src ; fi
if [ ! -d kanapi ] 
then 
	if [ "${USE_LOCAL}" = "1" ] 
	then
		git clone ${REPO_BASE} kanapi
	else
		git clone https://github.com/jdanecki/kanapi64.git kanapi
	fi
else
	pushd kanapi
	git pull
	popd
fi

docker create -i -t --name kanapi-${NAME}-${VER} \
 	--privileged \
   --cap-add=ALL \
   --device /dev:/dev \
   --ipc host \
    -v ${DIR}/kanapi:/kanapi_build/kanapi \
    -v ${HOME}/src:/${KANAPI_VER}/home/src \
    -v ${HOME}/.ccache:/${KANAPI_VER}/home/.ccache \
    -e HOME=/${KANAPI_VER}/home kanapi/kanapi-${NAME}:${BASE_FOR_UPDATE} \
	/bin/bash

