#!/bin/bash

# TODO: allow to specify version
# TODO: allow using a file
# TODO: deps

KANAPI_VER=$(cat KANAPI_VER)
sdir=$(dirname "$(realpath "$0")")
cd $sdir
CHROOT_DIR=${sdir}/chroot
KANAPI_DIR=${CHROOT_DIR}/kanapi_${KANAPI_VER}
PACKAGES_DIR=${KANAPI_DIR}/packages
KANAPI_BIN=${KANAPI_DIR}/bin

KANAPI_DIR_GLOBAL=/kanapi_${KANAPI_VER}
PACKAGES_DIR_GLOBAL=${KANAPI_DIR_GLOBAL}/packages
KANAPI_BIN_GLOBAL=${KANAPI_DIR_GLOBAL}/bin

get_version() {
  pkg_trimmed=$(echo $1 | tr "-" "_")
  line=$(grep "^${pkg_trimmed}_ver=" config.kanapi)
  pkg_version=${line#*=}
  pkg_version=${pkg_version#(}
  pkg_version=${pkg_version%)}
  if [[ "$pkg_version" == "" ]]; then
    echo "Couldn't find version for ${pkg}"
    echo "Does the package exist?"
    exit 1
  fi
}

# FIXME: do not copy from update_include (create "library" script)
search_in_dir() {
  if [ -d $2 ]; then
    name=$(echo $2 | sed "s@$1\/@@")
    #	echo "dir: $1 --- $2 -> $name"
    if [ ! -d $name ]; then mkdir -p $name; fi
    for f in $2/*; do
      search_in_dir $1 $f
    done
  else
    name=$(echo $2 | sed "s@$1\/@@")
    #	echo "fil: $1 --- $2 -> $name"
    ln -sf ${PACKAGES_DIR_GLOBAL}/$2 $name
  fi
}

# FIXME: move to "library" script to use with `pkg` later on
# TODO: also deal with cmake, pkgconfig, aclocal
install_package_links() {
  cd ${PACKAGES_DIR}
  p=$1
  PREFIX=${PACKAGES_DIR}/$p
  PREFIX_GLOBAL=${PACKAGES_DIR_GLOBAL}/$p
  if [ ! -d ${KANAPI_BIN} ]; then mkdir ${KANAPI_BIN}; fi
  if [ -d ${PREFIX}/bin ]; then
    ln -sf ${PREFIX_GLOBAL}/bin/* ${KANAPI_BIN}
  fi
  if [ -d ${PREFIX}/sbin ]; then
    ln -sf ${PREFIX_GLOBAL}/sbin/* ${KANAPI_BIN}
  fi
  if [ -d ${PREFIX}/usr/bin ]; then
    ln -sf ${PREFIX_GLOBAL}/usr/bin/* ${KANAPI_BIN}
  fi
  if [ -d ${PREFIX}/usr/sbin ]; then
    ln -sf ${PREFIX_GLOBAL}/usr/sbin/* ${KANAPI_BIN}
  fi

  for f in $p/lib/lib*.so* $p/lib/lib*.a $p/lib/lib*.la $p/lib64/lib*.so* $p/lib64/lib*.a $p/lib64/lib*.la; do
    if [ -f $f ]; then
      ln -sf ${PACKAGES_DIR_GLOBAL}/$f ${PACKAGES_DIR}/libs/$(basename $f)
    fi
  done
  if [ -d $p/include ]; then
    for fd in $p/include/*; do
      dir=$(basename $p)
      if [ "${dir:0:3}" = "gcc" -o "${dir:0:5}" = "glibc" ]; then
        #echo "don't link compiler $dir"
        continue
      else
        #echo "$p ($dir)-> $fd"
        search_in_dir $p $fd
      fi
    done
  fi
}

# FIXME: cleanup
install_package() {
  get_version $1
  cd ${sdir}/kanapi-clone/kanapi_system
  pkg_ver=$1-$pkg_version
  path=$(find -name "$pkg_ver")
  cd ${sdir}/..
  cd $(dirname $path)
  mkdir ../build/$pkg_ver
  cd ../build/$pkg_ver
  pkg_kanapi=${pkg}.kanapi
  ln -sf ../../packages/${pkg_ver}/${pkg_kanapi}
  pkg_kanapi ${pkg_kanapi} verify
  echo installing $pkg_ver
  if [[ ! -f kanapi_verify ]]; then
    export DESTDIR=$CHROOT_DIR
    pkg_kanapi ${pkg_kanapi} download
    pkg_kanapi ${pkg_kanapi} prepare
    pkg_kanapi ${pkg_kanapi} configure
    pkg_kanapi ${pkg_kanapi} build
    pkg_kanapi ${pkg_kanapi} install
    rmdir /kanapi_${KANAPI_VER}/packages/${pkg_ver} # NOTE: gets rid of the line with `mkdir ${PREFIX}` that doesn't care about DESTDIR in `settings` script
  else
    cp -r /kanapi_${KANAPI_VER}/packages/${pkg_ver} ${PACKAGES_DIR}
  fi
  install_package_links ${pkg_ver}
}

install_layer() {
  cd ${sdir}/..
  if [ ! -d $1 ]; then
    echo "layer $1 doesn't exist"
    exit 1
  fi
  echo "in install layer"
  cd ${sdir}
  git clone ../.. kanapi-clone-for-layer-build
  cd ${sdir}/kanapi-clone-for-layer-build/kanapi_system/$1/build
  ./verify $1
  for d in *; do
    if [ -d $d ]; then
      echo installing $d
      if [[ "$d" == "busybox-1.37.0" ]]; then # FIXME: busybox will get removed in kanapi 13. This is a hack to simplify stuff
        continue
      fi
      rsync -a --info=progress2 /kanapi_${KANAPI_VER}/packages/"$d" "${PACKAGES_DIR}/"
      install_package_links $d
    fi
    cd ${sdir}/kanapi-clone-for-layer-build/kanapi_system/$1/build
  done
}

mkdir -p ${KANAPI_DIR}/packages/libs
mkdir -p ${KANAPI_DIR}/packages/include
# TODO: maybe deal with these too?
# mkdir -p ${KANAPI_DIR}/icons
# mkdir -p ${KANAPI_DIR}/desktop
mkdir -p ${KANAPI_DIR}/bin

if [ -d kanapi-clone ]; then
  cd kanapi-clone
  git pull
  cd ..
else
  git clone ../.. kanapi-clone
fi

if [[ $# -gt 0 ]]; then
  for pkg in $@; do
    if [[ ${pkg:0:1} == "@" ]]; then # detect `@` layer tag
      install_layer ${pkg:1}
    else
      install_package $pkg
    fi
    cd ${sdir}
  done
fi

cd ${sdir}/chroot
mkdir -p kanapi_build
cd kanapi_build
if [ -d kanapi64 ]; then
  cd kanapi64
  git pull
  cd ..
else
  git clone ../../../.. kanapi64
fi
ln -sf kanapi64 kanapi
ln -sf ${KANAPI_BIN_GLOBAL} ${CHROOT_DIR}/bin
ln -sf /kanapi_build/kanapi/kanapi_system/scripts/pkg_kanapi ${KANAPI_BIN}
ln -sf /kanapi_build/kanapi/kanapi_system/scripts/pkg ${KANAPI_BIN}
ln -sf /kanapi_build/kanapi/kanapi_system/scripts/pkg_dev ${KANAPI_BIN}
mkdir -p ${CHROOT_DIR}/usr
ln -sf ${KANAPI_BIN_GLOBAL} ${CHROOT_DIR}/usr/bin
