#!/bin/bash

BUILD_VERSION=0.10

ln -sf /kanapi_build/kanapi/kanapi_system/scripts/pkg_kanapi /bin/pkg_kanapi
mkdir -p /kanapi_${BUILD_VERSION}
ln -sfn /kanapi_${BUILD_VERSION}/packages/include /usr/local/include
cd /kanapi_build/kanapi/kanapi_system/sbs/build
if [ "${TRAVIS}" = "true" ]
then
	./install sbs ci
else
	./install sbs verbose
fi

cd /kanapi_build/kanapi/kanapi_system/sbs
cat prepare_sbs_docker.template | sed "s/@SBS_BUILD@/8/" > prepare_sbs_docker
chmod +x prepare_sbs_docker
./prepare_sbs_docker

